### ISSUE TITLE
Empty space in font preview window

### ISSUE THREAD

**Issue by viterzbayraku** [Mark2Mark/variable-font-preview#22]
Hello, Mark. I have question about a lot of empty space on top of preview window. It's ok?
For me it's very unuseful and uncomfortable. Sorry )

![Знімок екрана 2023-05-19 о 15 26 49](https://github.com/Mark2Mark/variable-font-preview/assets/4019353/d0b19425-5ada-419f-8551-3e0897aad1b5)

**Comment by Mark2Mark** [comment]
Hi @viterzbayraku 

this could be a scaling issue. That should be fixed with a newer version (or could be even introduced for other users)

1. may I ask you to tell me your plugin version?

- In the Glyphs Menu "Script" > "Open Scripts Folder"
- Next to that "Scripts" folder in the Finder is a "Repositories" folder
- In that "Repositories" folder, go to "variable-font-preview"
- In that folder right click on "Variable Font Preview X.glyphsReporter" and click "Get Info"
- The Info window will show a Version entry. That Version number is what I need

2. What monitor are you on?

Thanks in advance

**Comment by 75th** [comment]
I'm the guy from the previous thread, and this issue is unfixed and unchanged for me in plugin version 3.4.3.

**Comment by viterzbayraku** [comment]
> Hi @viterzbayraku
> 
> this could be a scaling issue. That should be fixed with version 3.4.3 which is live already but Glyphs might need a moment to fetch the new version.
> 
> 1. What is your plugin version?
> 
> * In the Glyphs Menu "Script" > "Open Scripts Folder"
> * Next to that "Scripts" folder in the Finder is a "Repositories" folder
> * In that "Repositories" folder, go to "variable-font-preview"
> * In that folder right click on "Variable Font Preview X.glyphsReporter" and click "Get Info"
> * The Info window will show a Version entry. That Version number is what I need
> 
> or run this in the Macro Panel and copy the output here as text
> 
> ```python
> from AppKit import NSBundle
> bdl = NSBundle.bundleForClass_(NSClassFromString("MFVariableFontPreviewX"))
> print(bdl.objectForInfoDictionaryKey_("CFBundleShortVersionString"))
> ```
> 
> 2. What monitor are you on?
> 3. Which UPM does your font have?
> 
> Thanks in advance

1. 3.4.3
2. 13,3' (1440 x 900)
3. 1000 units per em

**Comment by Mark2Mark** [comment]
Would any of you mind to send me a font with that problem? @viterzbayraku @75th 

You can make a copy of your font, delete all glyphs but one or two. If you want, remove some sensitive information from the font info. 

I cannot reproduce it here so maybe your fonts can help debugging. 

Thanks so much

**Comment by viterzbayraku** [comment]
> ## Another version is live: 3.4.4
> 👉 Please check once more with that version.
> 
> 👉 In case Glyphs does not pull the latest version, you can force it by deleting the plugin file from the "Repositories" folder and and re-install from the Plugin Manager.
> 
> ## If it is still not fixed with version 3.4.4:
> Would any of you mind to send me a font with that problem? @viterzbayraku @75th
> 
> You can make a copy of your font, delete all glyphs but one or two. If you want, remove some sensitive information from the font info.
> 
> I cannot reproduce it here so maybe your fonts can help debugging.
> 
> Thanks so much

The problem is fixed in the new version. Thank you!

**Comment by 75th** [comment]
For me as well! Thanks!

**Comment by Mark2Mark** [comment]
Thank you both so much for your help. This bug was haunting me ever since 👏 
@75th @viterzbayraku

**Comment by Mark2Mark** [comment]
Hey @75th @viterzbayraku 

Sorry for tagging you again. May I ask you to observe this scaling issue once more?

I made some big changes in version **3.4.5** which should be pulled soon (or force install it again as described above). These changes should hopefully not change anything for you to the worse again, but the code is way cleaner.

I hope you will still have the preview scaled nicely in all occasions.

Thanks so much in advance!

**Comment by viterzbayraku** [comment]
> Hey @75th @viterzbayraku
> 
> Sorry for tagging you again. May I ask you to observe this scaling issue once more?
> 
> I made some big changes in version **3.4.5** which should be pulled soon (or force install it again as described above). These changes should hopefully not change anything for you to the worse again, but the code is way cleaner.
> 
> I hope you will still have the preview scaled nicely in all occasions.
> 
> Thanks so much in advance!

I will try!

**Comment by Mark2Mark** [comment]
Note to self: first user reported via email, that it still works.

**Comment by Mark2Mark** [comment]
closing due to lack of response.

Reopen if needed, **but** comment your Glyphs and Plugin Versions, plus describing the issue again.
